Feature junit testing
wolox-training/jst-java pull request #12
Opened 2021-05-18 13:18 UTC by JoelIvanStella

## Summary
- JUnit testing of controllers, repositories and models
## Trello Card
https://trello.com/c/mo61gIbb

2021-05-18 13:29 UTC, torsello requested changes
Good job, I leave you some comments

2021-05-18 13:29 UTC, torsello commented on src/test/java/com/wolox/training/controllers/BookControllerTest.java
> +                        + "    \"id\": 0,\n"
Hi Joel, we used to put this JSONs in a file, so you can re-use it. But for me, now you can just replace it with a Constant.

2021-05-18 13:29 UTC, torsello commented on src/test/java/com/wolox/training/controllers/UserControllerTest.java
> +                        + "    \"id\": 0,\n"
In this case, the same. Use constants

2021-05-18 17:49 UTC, torsello approved these changes
LGTM!

2021-05-21 14:08 UTC, jdhiguita approved these changes
Great job!

2021-05-21 16:10 UTC, merged